### PR TITLE
update composer dependencies

### PR DESCRIPTION
**Pull request by prolic**
Fix for: https://github.com/ZF-Commons/ZfcUserDoctrineMongoODM/issues/18 and https://github.com/ZF-Commons/ZfcUserDoctrineMongoODM/issues/17

### CODE REVIEW

**Comment by Danielss89** [comment]
Thank you. Composer install/update fails with:
```
- Installation request for doctrine/doctrine-mongo-odm-module 0.8.2 -> satisfiable by doctrine/doctrine-mongo-odm-module[0.8.2].
- doctrine/doctrine-mongo-odm-module 0.8.2 requires doctrine/mongodb-odm ~1.0.0-beta9@dev -> no matching package found.
```
which is pretty weird as a composer install in doctrine/doctrine-mongo-odm-modul 0.8.2 works perfectly. I've pinged @ocramius on IRC an awaits his answer.

**Comment by prolic** [comment]
@Danielss89 you should use doctrine-mongo-odm-module dev-master, the 0.8.2 is pretty outdated.

**Comment by gabrielsch** [comment]
@Danielss89 could you take a look on it? I think there are many people with this problem

**Comment by Danielss89** [comment]
I can't merge this PR yet, dependencies are still erroring
```
ZfcUserDoctrineMongoODM git:(prolic-master) composer install
Loading composer repositories with package information
Installing dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for doctrine/doctrine-mongo-odm-module dev-master -> satisfiable by doctrine/doctrine-mongo-odm-module[dev-master].
    - doctrine/doctrine-mongo-odm-module dev-master requires doctrine/doctrine-module 0.9.* -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```
the dev-master branch requires doctrineModule v. 0.9 which haven't been tagged yet.

**Comment by Danielss89** [comment]
Fixed in #21 
Thx.

**Pull request closed without merging**
